name: babymonitarr
description: "BabyMonitarr - Baby monitoring with real-time audio streaming"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_webrtc: ^1.3.1
  signalr_netcore: ^1.4.4
  logging: ^1.3.0
  flutter_local_notifications: ^20.0.0
  permission_handler: ^12.0.1
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.0.17
  provider: ^6.1.2
  vibration: ^3.1.7
  validators: ^3.0.0
  google_fonts: ^8.0.2
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  min_sdk_android: 21
  image_path_android: "assets/icon/icon_android.png"
  adaptive_icon_background: "#1D1D23"
  adaptive_icon_foreground: "assets/icon/icon_android.png"
  ios: true
  image_path_ios: "assets/icon/icon_ios.png"
  remove_alpha_ios: true
  background_color_ios: "#1D1D23"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#1D1D23"
    theme_color: "#1D1D23"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 256

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
