"""Generate the dev-build launcher icons from the release ones.

The release icons live in android/app/src/main/res (generated by
flutter_launcher_icons). This script copies them into
android/app/src/debug/res with a "DEV" band composited on, so the debug
build (applicationIdSuffix ".dev") is distinguishable in the app drawer.

Re-run after regenerating icons:
    python tool/badge_dev_icon.py
"""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
MAIN_RES = ROOT / "android" / "app" / "src" / "main" / "res"
DEBUG_RES = ROOT / "android" / "app" / "src" / "debug" / "res"

DENSITIES = ["mdpi", "hdpi", "xhdpi", "xxhdpi", "xxxhdpi"]
BAND_COLOR = (255, 109, 0, 235)  # orange, readable on the dark app background
TEXT_COLOR = (255, 255, 255, 255)
LABEL = "DEV"

FONT_CANDIDATES = [
    "C:/Windows/Fonts/arialbd.ttf",
    "C:/Windows/Fonts/segoeuib.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
]


def load_font(size: int) -> ImageFont.FreeTypeFont:
    for candidate in FONT_CANDIDATES:
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default(size)


def badge(src: Path, dst: Path, top: float, bottom: float) -> None:
    """Composite the DEV band over `src` between the given height fractions."""
    image = Image.open(src).convert("RGBA")
    width, height = image.size
    y0, y1 = int(height * top), int(height * bottom)

    overlay = Image.new("RGBA", image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)
    draw.rectangle([0, y0, width, y1], fill=BAND_COLOR)

    font = load_font(max(8, int((y1 - y0) * 0.72)))
    draw.text(
        ((width - 1) / 2, (y0 + y1) / 2),
        LABEL,
        font=font,
        fill=TEXT_COLOR,
        anchor="mm",
    )

    dst.parent.mkdir(parents=True, exist_ok=True)
    Image.alpha_composite(image, overlay).save(dst)
    print(f"wrote {dst.relative_to(ROOT)}")


def main() -> None:
    for density in DENSITIES:
        # Legacy icon: full-bleed, so the band can sit low.
        badge(
            MAIN_RES / f"mipmap-{density}" / "ic_launcher.png",
            DEBUG_RES / f"mipmap-{density}" / "ic_launcher.png",
            0.62,
            0.84,
        )
        # Adaptive foreground: the XML insets it by 16% and the launcher mask
        # crops the outer edges, so keep the band inside the safe zone.
        badge(
            MAIN_RES / f"drawable-{density}" / "ic_launcher_foreground.png",
            DEBUG_RES / f"drawable-{density}" / "ic_launcher_foreground.png",
            0.71,
            0.91,
        )


if __name__ == "__main__":
    main()
